# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: lstm_object_detection/protos/input_reader_google.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from object_detection.protos import input_reader_pb2 as object__detection_dot_protos_dot_input__reader__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='lstm_object_detection/protos/input_reader_google.proto',
  package='lstm_object_detection.protos',
  syntax='proto2',
  serialized_pb=_b('\n6lstm_object_detection/protos/input_reader_google.proto\x12\x1clstm_object_detection.protos\x1a*object_detection/protos/input_reader.proto\"\x80\x02\n\x11GoogleInputReader\x12^\n\x1ctf_record_video_input_reader\x18\x01 \x01(\x0b\x32\x36.lstm_object_detection.protos.TFRecordVideoInputReaderH\x00\x32{\n\x13google_input_reader\x12,.object_detection.protos.ExternalInputReader\x18\xbc\x03 \x01(\x0b\x32/.lstm_object_detection.protos.GoogleInputReaderB\x0e\n\x0cinput_reader\"\xf3\x01\n\x18TFRecordVideoInputReader\x12\x12\n\ninput_path\x18\x01 \x03(\t\x12g\n\tdata_type\x18\x02 \x01(\x0e\x32?.lstm_object_detection.protos.TFRecordVideoInputReader.DataType:\x13TF_SEQUENCE_EXAMPLE\x12\x14\n\x0cvideo_length\x18\x03 \x01(\x05\"D\n\x08\x44\x61taType\x12\x0f\n\x0bUNSPECIFIED\x10\x00\x12\x0e\n\nTF_EXAMPLE\x10\x01\x12\x17\n\x13TF_SEQUENCE_EXAMPLE\x10\x02')
  ,
  dependencies=[object__detection_dot_protos_dot_input__reader__pb2.DESCRIPTOR,])
_sym_db.RegisterFileDescriptor(DESCRIPTOR)



_TFRECORDVIDEOINPUTREADER_DATATYPE = _descriptor.EnumDescriptor(
  name='DataType',
  full_name='lstm_object_detection.protos.TFRecordVideoInputReader.DataType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='UNSPECIFIED', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='TF_EXAMPLE', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='TF_SEQUENCE_EXAMPLE', index=2, number=2,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=567,
  serialized_end=635,
)
_sym_db.RegisterEnumDescriptor(_TFRECORDVIDEOINPUTREADER_DATATYPE)


_GOOGLEINPUTREADER = _descriptor.Descriptor(
  name='GoogleInputReader',
  full_name='lstm_object_detection.protos.GoogleInputReader',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='tf_record_video_input_reader', full_name='lstm_object_detection.protos.GoogleInputReader.tf_record_video_input_reader', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
    _descriptor.FieldDescriptor(
      name='google_input_reader', full_name='lstm_object_detection.protos.GoogleInputReader.google_input_reader', index=0,
      number=444, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=True, extension_scope=None,
      options=None),
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='input_reader', full_name='lstm_object_detection.protos.GoogleInputReader.input_reader',
      index=0, containing_type=None, fields=[]),
  ],
  serialized_start=133,
  serialized_end=389,
)


_TFRECORDVIDEOINPUTREADER = _descriptor.Descriptor(
  name='TFRecordVideoInputReader',
  full_name='lstm_object_detection.protos.TFRecordVideoInputReader',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='input_path', full_name='lstm_object_detection.protos.TFRecordVideoInputReader.input_path', index=0,
      number=1, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='data_type', full_name='lstm_object_detection.protos.TFRecordVideoInputReader.data_type', index=1,
      number=2, type=14, cpp_type=8, label=1,
      has_default_value=True, default_value=2,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='video_length', full_name='lstm_object_detection.protos.TFRecordVideoInputReader.video_length', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _TFRECORDVIDEOINPUTREADER_DATATYPE,
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=392,
  serialized_end=635,
)

_GOOGLEINPUTREADER.fields_by_name['tf_record_video_input_reader'].message_type = _TFRECORDVIDEOINPUTREADER
_GOOGLEINPUTREADER.oneofs_by_name['input_reader'].fields.append(
  _GOOGLEINPUTREADER.fields_by_name['tf_record_video_input_reader'])
_GOOGLEINPUTREADER.fields_by_name['tf_record_video_input_reader'].containing_oneof = _GOOGLEINPUTREADER.oneofs_by_name['input_reader']
_TFRECORDVIDEOINPUTREADER.fields_by_name['data_type'].enum_type = _TFRECORDVIDEOINPUTREADER_DATATYPE
_TFRECORDVIDEOINPUTREADER_DATATYPE.containing_type = _TFRECORDVIDEOINPUTREADER
DESCRIPTOR.message_types_by_name['GoogleInputReader'] = _GOOGLEINPUTREADER
DESCRIPTOR.message_types_by_name['TFRecordVideoInputReader'] = _TFRECORDVIDEOINPUTREADER

GoogleInputReader = _reflection.GeneratedProtocolMessageType('GoogleInputReader', (_message.Message,), dict(
  DESCRIPTOR = _GOOGLEINPUTREADER,
  __module__ = 'lstm_object_detection.protos.input_reader_google_pb2'
  # @@protoc_insertion_point(class_scope:lstm_object_detection.protos.GoogleInputReader)
  ))
_sym_db.RegisterMessage(GoogleInputReader)

TFRecordVideoInputReader = _reflection.GeneratedProtocolMessageType('TFRecordVideoInputReader', (_message.Message,), dict(
  DESCRIPTOR = _TFRECORDVIDEOINPUTREADER,
  __module__ = 'lstm_object_detection.protos.input_reader_google_pb2'
  # @@protoc_insertion_point(class_scope:lstm_object_detection.protos.TFRecordVideoInputReader)
  ))
_sym_db.RegisterMessage(TFRecordVideoInputReader)

_GOOGLEINPUTREADER.extensions_by_name['google_input_reader'].message_type = _GOOGLEINPUTREADER
object__detection_dot_protos_dot_input__reader__pb2.ExternalInputReader.RegisterExtension(_GOOGLEINPUTREADER.extensions_by_name['google_input_reader'])

# @@protoc_insertion_point(module_scope)
