# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: lstm_object_detection/protos/pipeline.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from object_detection.protos import pipeline_pb2 as object__detection_dot_protos_dot_pipeline__pb2
from lstm_object_detection.protos import quant_overrides_pb2 as lstm__object__detection_dot_protos_dot_quant__overrides__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='lstm_object_detection/protos/pipeline.proto',
  package='lstm_object_detection.protos',
  syntax='proto2',
  serialized_pb=_b('\n+lstm_object_detection/protos/pipeline.proto\x12\x1clstm_object_detection.protos\x1a&object_detection/protos/pipeline.proto\x1a\x32lstm_object_detection/protos/quant_overrides.proto\"\x95\x03\n\tLstmModel\x12\x1b\n\x13train_unroll_length\x18\x01 \x01(\x05\x12\x1a\n\x12\x65val_unroll_length\x18\x02 \x01(\x05\x12\x1d\n\x10lstm_state_depth\x18\x03 \x01(\x05:\x03\x32\x35\x36\x12\x19\n\x11\x64\x65pth_multipliers\x18\x04 \x03(\x02\x12\'\n\x17train_interleave_method\x18\x05 \x01(\t:\x06RANDOM\x12%\n\x16\x65val_interleave_method\x18\x06 \x01(\t:\x05SKIP9\x12\x1d\n\x11lstm_state_stride\x18\x07 \x01(\x05:\x02\x33\x32\x12\x1c\n\rflatten_state\x18\x08 \x01(\x08:\x05\x66\x61lse\x12\x1d\n\x0epre_bottleneck\x18\t \x01(\x08:\x05\x66\x61lse\x12\x1a\n\x0bscale_state\x18\n \x01(\x08:\x05\x66\x61lse\x12\x18\n\nclip_state\x18\x0b \x01(\x08:\x04true\x12\x1b\n\x0cis_quantized\x18\x0c \x01(\x08:\x05\x66\x61lse\x12\x16\n\x07low_res\x18\r \x01(\x08:\x05\x66\x61lse:p\n\nlstm_model\x12\x30.object_detection.protos.TrainEvalPipelineConfig\x18\xd4\xca\x8d\x62 \x01(\x0b\x32\'.lstm_object_detection.protos.LstmModel:z\n\x0fquant_overrides\x12\x30.object_detection.protos.TrainEvalPipelineConfig\x18\xbd\xa6\xaau \x01(\x0b\x32,.lstm_object_detection.protos.QuantOverrides')
  ,
  dependencies=[object__detection_dot_protos_dot_pipeline__pb2.DESCRIPTOR,lstm__object__detection_dot_protos_dot_quant__overrides__pb2.DESCRIPTOR,])
_sym_db.RegisterFileDescriptor(DESCRIPTOR)


LSTM_MODEL_FIELD_NUMBER = 205743444
lstm_model = _descriptor.FieldDescriptor(
  name='lstm_model', full_name='lstm_object_detection.protos.lstm_model', index=0,
  number=205743444, type=11, cpp_type=10, label=1,
  has_default_value=False, default_value=None,
  message_type=None, enum_type=None, containing_type=None,
  is_extension=True, extension_scope=None,
  options=None)
QUANT_OVERRIDES_FIELD_NUMBER = 246059837
quant_overrides = _descriptor.FieldDescriptor(
  name='quant_overrides', full_name='lstm_object_detection.protos.quant_overrides', index=1,
  number=246059837, type=11, cpp_type=10, label=1,
  has_default_value=False, default_value=None,
  message_type=None, enum_type=None, containing_type=None,
  is_extension=True, extension_scope=None,
  options=None)


_LSTMMODEL = _descriptor.Descriptor(
  name='LstmModel',
  full_name='lstm_object_detection.protos.LstmModel',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='train_unroll_length', full_name='lstm_object_detection.protos.LstmModel.train_unroll_length', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='eval_unroll_length', full_name='lstm_object_detection.protos.LstmModel.eval_unroll_length', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='lstm_state_depth', full_name='lstm_object_detection.protos.LstmModel.lstm_state_depth', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=True, default_value=256,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='depth_multipliers', full_name='lstm_object_detection.protos.LstmModel.depth_multipliers', index=3,
      number=4, type=2, cpp_type=6, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='train_interleave_method', full_name='lstm_object_detection.protos.LstmModel.train_interleave_method', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=True, default_value=_b("RANDOM").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='eval_interleave_method', full_name='lstm_object_detection.protos.LstmModel.eval_interleave_method', index=5,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=True, default_value=_b("SKIP9").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='lstm_state_stride', full_name='lstm_object_detection.protos.LstmModel.lstm_state_stride', index=6,
      number=7, type=5, cpp_type=1, label=1,
      has_default_value=True, default_value=32,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='flatten_state', full_name='lstm_object_detection.protos.LstmModel.flatten_state', index=7,
      number=8, type=8, cpp_type=7, label=1,
      has_default_value=True, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='pre_bottleneck', full_name='lstm_object_detection.protos.LstmModel.pre_bottleneck', index=8,
      number=9, type=8, cpp_type=7, label=1,
      has_default_value=True, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='scale_state', full_name='lstm_object_detection.protos.LstmModel.scale_state', index=9,
      number=10, type=8, cpp_type=7, label=1,
      has_default_value=True, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='clip_state', full_name='lstm_object_detection.protos.LstmModel.clip_state', index=10,
      number=11, type=8, cpp_type=7, label=1,
      has_default_value=True, default_value=True,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='is_quantized', full_name='lstm_object_detection.protos.LstmModel.is_quantized', index=11,
      number=12, type=8, cpp_type=7, label=1,
      has_default_value=True, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='low_res', full_name='lstm_object_detection.protos.LstmModel.low_res', index=12,
      number=13, type=8, cpp_type=7, label=1,
      has_default_value=True, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=170,
  serialized_end=575,
)

DESCRIPTOR.message_types_by_name['LstmModel'] = _LSTMMODEL
DESCRIPTOR.extensions_by_name['lstm_model'] = lstm_model
DESCRIPTOR.extensions_by_name['quant_overrides'] = quant_overrides

LstmModel = _reflection.GeneratedProtocolMessageType('LstmModel', (_message.Message,), dict(
  DESCRIPTOR = _LSTMMODEL,
  __module__ = 'lstm_object_detection.protos.pipeline_pb2'
  # @@protoc_insertion_point(class_scope:lstm_object_detection.protos.LstmModel)
  ))
_sym_db.RegisterMessage(LstmModel)

lstm_model.message_type = _LSTMMODEL
object__detection_dot_protos_dot_pipeline__pb2.TrainEvalPipelineConfig.RegisterExtension(lstm_model)
quant_overrides.message_type = lstm__object__detection_dot_protos_dot_quant__overrides__pb2._QUANTOVERRIDES
object__detection_dot_protos_dot_pipeline__pb2.TrainEvalPipelineConfig.RegisterExtension(quant_overrides)

# @@protoc_insertion_point(module_scope)
